# Generated by Django 5.0.6 on 2024-05-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="mobile",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
